---
instance:
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/jackusm/home-ops.git"
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
