# NOTE: placeholders until you fill in your Pushover credentials and encrypt.
# 1. User key: shown on your pushover.net dashboard ("Your User Key")
# 2. Application token: create an application at https://pushover.net/apps/build
# 3. Replace the placeholders below
# 4. sops --encrypt --in-place kubernetes/apps/observability/kube-prometheus-stack/app/alertmanager-secret.sops.yaml
# Do not commit/push this file while it contains plaintext.
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:W82/mGoyI3AuPPKvG9XCsnZlQXgblb9cHX3gV9A5,iv:xLhKrTSXClE4Ww+dhRbB0XIPvUSQQ25fgdU0LC3rRS8=,tag:O5MdaY1dTV8ZAtMULwwf9g==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:2Wy+XxJNFFZHBqlpb4i/BuXW8B4qS3KejLFRHSjN,iv:KLLnQsXTO6koKoCSlflAIHI1I9To956kUgTlzgsHwVQ=,tag:BmjumeAHWCpLh8/LUhoYvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycHV3RXlqT2puTkhUOHZq
        RFh1M2tWLy8rMmVVOGVUaDRucUp6WFJNelc0CldnUDllWVExMUNyNmdRclBXTGJM
        R1A0SGlsNHZqazlacWxYb25UZTl1Q2cKLS0tIGhQOGwvQlV1NW1YMVhFTUd3ZUdR
        WVBJelJzdEpFNGgvcmNJUTJKMWh3L3cK73Rup8f9lT4rRHSBMh05CY9s/6fhhJ7D
        trM3dMYMs7or4t4iYyiY4xH1QIKyiJDY8m4bZ4GZVQcjRfSKIZ81fA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T10:57:05Z"
  mac: ENC[AES256_GCM,data:/1ai5lTdz5rlt3uIaWUlqFerXJHYVU2rTztpnKYoDEvtSPxdjayIdKZZCwpiEheNQzYFzLHWKuFUC0Rlb9l3+9emMSFddCLLLw8pAuqYST6pmnR1sAgtSfNXGKGKVHB8I7CVs937fpLzeg6dWPKW0PnPSrR4X6fGZ7ELIbI+Sio=,iv:VNvxMQ/VWXOl7S9AdnOQYBPI5YODjBXwNRVnXH/tpH8=,tag:tSPu45JLe2dSA4XPXTR3lg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
