apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ppU6tQHcIKAFgBoInCVo/L2pnLGLw0dT6Ke+CCmPG+0fMYrZuE9F4w==,iv:VfwnHm0vK4+j7Rp9CxEpgeTzE1fvlSdC5yYFQSP+89M=,tag:fFdsbK3HfvRrtMaywhcwJg==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueUhjeXpoczkvbGhTSEVQ
        SjFOS3FzNnR5Mi9tYUpqaWRXSlZxbm9IMmhrCm5vUEh3dFZvdG9RbTNZaWl3bGQx
        dEVWUEFBVDFMdGFMSGFaa2Z3Y1U1QVUKLS0tIEtYQ2pNSzFDSSs5cjkxci9menVv
        RWNFYVF1TmhhZjBORXB5eEZUdnd4MFkKhKSRDGPWGpS2+eQnPTgbOeUAiwewd+DT
        FOyx6SP966UjJ1FRqfRD9FKnKouugbq8to824anrRNfLABPHMkUJLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T15:44:42Z"
  mac: ENC[AES256_GCM,data:Cr3+6/kuzTyOAWUChMVyEFCivHA/PiE/37UZ6587zPyzCSmFm2SinZR2yxHBIq6gUQPMYrl9LWUtj7EVrfJqzlcMZlZVsG2Yxt2zyGPP/JWzLl94Sv2IdnD7QeYnfNblTkdDwP76KAaWaJEGMGG8sCoSvLscp7Ts89o3IVLnsgw=,iv:s/zQNiQS5qcf9xE3ffFhJMQRp7whiS00ljvQpXw2guA=,tag:eodZxYd4mPSQJpj8ha+urQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
