apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pefdbGy6JVA6OcgT1Z1DZBresuDEWfsmhLLN2+IPpHNDoAPh+j0xtA==,iv:oZC9o0DUpvd8VIxgo1pPlh07aUOa7U7uaHUerBc5428=,tag:ohiHIctvSafvsFQkqMXdnQ==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NGVobUsvZkR5bnUrZUJS
        K3VEWUl6SnBzdFhhd0FHMXQvUEZ2cGt0VFhjCko3WHBrbnZkVzdsdW1GVHEvVFRC
        VGx5azRIZmJKQjdSSC8vKzZPWUVyZ0EKLS0tIDhsemNJckFrMnNwNXRnMkM2SFpB
        N00rblcxZ2x3NVlWOTlZQjhZRHFHcXcKiDYl/0wpPsJgz8E6FZsE1t7g+j5JOMKv
        dSP+6MoNDyVY5xYpuHM8YcX3hVq9SlEjAxx76VfGV/S/XQ2btT7pbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T01:46:09Z"
  mac: ENC[AES256_GCM,data:2R5CKjCfKkK9NY6sqSmVkRAPHvCsUK7/OAF7qhIhHzi9sHmfCiGZHrPxeydhx7Bcqgw5IVf58aHSSRs9+NIuLPJKME684Gn9pdwicrxATyUHREy0L1xwujmDGszaIs3/zZ7kUJFpYfO7PW8K2ovom1vXvOc0FiPbhyGg9S0J79I=,iv:sdkdiiouuhJwyZhSl4hGsIDcN/L2c/keVaSZd0S5U6g=,tag:Y4UjPDH4UoqVwlaDMBQSXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
