apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/y8xxwEF5y22,iv:vsODpgPBChxgetx13xzlDXhik9vLgGs3uMw3tSyQk9g=,tag:eQ+EnGfH8qNtZ3AgQIwwsw==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N3Y2eFF6dGczNTRSeDRu
        ZU9sTS9aN2NyVWt0cC9XT1pBTzB6K1lNbHpNCmZ2UjZBdVpDOURwTkRkcHRBSHVX
        TklYVWVVbDdZS1hwVUVGd2xRYmJvc0kKLS0tIERpWjUwTXpQdCtPVnNZdWx1WVdv
        ZGpKOHduZ0RUY2o0Rm5rU1dza3ZHa1EKl4CHISoImimiiaTops2n47n/THcb+nnM
        lx2/SjbKb64/AWU4n+aDwBEYqrpP0E6FzQtA6z3YJiYfvRoSf9KJgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T01:46:09Z"
  mac: ENC[AES256_GCM,data:Q9G6SmHD0hg4g3nS7oowcpRMSBa5jUwLHfPZGWRapZ8i84sSx+fLydEKz3Yt8a110yT57LBlsopL+FxoVm+RV0B1NxyJozawkmxF84eQ8w4tzJJll6q6dmk7FZva3CdFzBvfI2I76e8rUkUsnWaFHsll4NL5DTLn+6mEtQW9pAQ=,iv:AJvkaQ2U3Lf6LRDuz8+wqMbEY/MoG/L0Fx9bJZnWFtU=,tag:rKuJnZmtJZBUWD2hJaGEiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
