apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6yuApjn9FTD1QjGWiw==,iv:Yu0qCYQ/6r+worNzYjq9Lq5d/uXbZug+hW4/OO0dw5E=,tag:a1V9T7BpXiAnlVel5F0ZZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2drSUEzdm5xZktZWmtN
        ZlVSNDlNZWRqSWxSZitLUGlYOXdpMUQ2QjBVCnJRZmJpS1hOaHA4dmJ5b2xwdFBX
        MEdIWE1SWHNZcExqZTN6dDNDRnFGT0EKLS0tIElRMU1wVlV6UEhNeFA0NVBQWWxP
        TVJNbEIySVpsamMxZjNPVFNVeWdJZGMKrs47TlZ7Lswgtm2oicTuwZI9xiDzEfP+
        AXAYtW6pnxLi213nl9x0BJQG0g0iCCpHmKfMg7dTWrsSIX44g3EvuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T19:51:14Z"
  mac: ENC[AES256_GCM,data:LeWNPnAwMTwhI9phzW5g8Fcv7JK6zCpmOiH65WaaLOdc4SzCSjBxrw3+mL28qYH2qB3RF5b+KdnMpAQcvIbiwAzzwf2b5KoLdc2QmjaYS2dCZuKb/Uxe8jsaR5A8vI03YcVC3QyY8H8Df4IIdGd23N727anpuoXiJIbm3jiVZ2k=,iv:CquKTJ0Uou0HH3ldFBluZW/uZH6C0Qfzh/bx6dNoZGM=,tag:H6gfHe7njsGaQV2sk5/tHw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
