apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:1mfMzp5TAtVJ,iv:pSWF/aGVhHNs1BMjyJ9PK8Uy1VrSvYG5f5YaPHmcXPA=,tag:n+png4VpW6myFQNWpW5mcg==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaDVMR2pFVHdGZnhyd2Fp
        UWxiSTA1YmQycGVxc081MG0wUUxyejZvdkRVCnhQY0VUOW8yOFdwSE9jY3V6Z3JW
        enVmUUVqck1VTUpUQUZMaW5LZmpsVjQKLS0tIG5MSTByOGczK3BBSFJaZWVweS9t
        L1ROWS9FNEU2enpOR0FTbWlZQVBVUkUKtfJPY0xYquBaExUYGFtDtQLLOWntF1kK
        8JlZUxZIqYWi+A1F8JWtLQQ/5noqEnXvi8ucBXdHt0NQD+XQa3EIqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T15:44:42Z"
  mac: ENC[AES256_GCM,data:9S3yJ8JtE1LJNQfx5262XjM4TE/mybPp+bkZ+CP4W4RSgebg41MXDzZUtCcKTdVir13gTTg64y17jk0Ms8VaomOcuNUy0Hz1k1Msyz5DHOoOYfAu3ORt6qSiMGgoUWSLFIse1mbYfZlEA6FMJ/rREaFdIVm3uch3m0NZG5frh8s=,iv:K2aKpuhrc/IMVydP94JOhtDqW60urdm8ngu45majsvc=,tag:mxu3GNfNasgzI0QVFKSP+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
