apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jEE08ED78oTC18ve10/S9P0Je+sLd6iElXU1Jj9gs/E=,iv:ob3UpUsUZzwYFZWHmGL0T2xjObxyGGn1RP+1J/16ZJY=,tag:LkonhY7Vr6pkeoho0r090Q==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RCtDa3RkMEgzUlJnNjVH
        WlM5a2lUUFNOSW1jU1grRDFnWG9CUmZDb0ZNCmJGRjBDMG9GbXNkTDBRcjhTYW9u
        SWhpQ1pFbEU5TVlycHVCY0hyY3VKMmsKLS0tIC83OG5FbUZPbThhci9NM2RGZ3V3
        aHM2bkp6UUhkQWR1SlVOUHo0NmpHb0kKu41FwnPgDOmvcmnYODlfLwv7IUph0p98
        KHQlFHyyE1mg3jFAlyR9Yq4O4lGDlMnc0a7VO9QW3ulWuqbA4XZMAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T01:46:09Z"
  mac: ENC[AES256_GCM,data:lM4oxuTevEwZM0W0Iy+5PEsvQe4IXxFtQbFm4PDSKjbWKS0A+WnczPdQsAH8Oqhwvb4BdH0rEX2fYipXbirsDg6M/olXhNwiawj/plhj1lXwu8EE1t9ysA71VDAXGVZ6xnPixlCCNFgxbTjClzMxgmVjz83hKx3SZbWXbi4yEuk=,iv:c2DotdKJ+4tPfOXyA988qNdeS/Qy9vlCtAvqIVPjcb0=,tag:iejaoILodylEuUZMkYCyxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
