apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DRgt5LZpJUxxp53MnuPiQWPJKLzrh6C3B39K3/4G8e0=,iv:FWEgLHVAnUeSTogIVSyHK9MZpbcv88qV1X50MOm4EL8=,tag:BB1PROTuXAcAEhvfp1Fwkw==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NlExSWMrbnZEWWhJaXdF
        WCtEVnY1bjhmMGh6ekw5SjA5K1lsY0pQakg4CkRwQW1SUkU4TkMzZDRHQWtIMmhi
        bmhqR21CWTJDRnZoTXIyVkpZVmlTYmsKLS0tIGt5aG1PenlyT2lvYzJ1SHN6QjZZ
        SUtzTlNzTDZxekFVQnEwWkdYdXUrQ2sKhRDA8BZ6qx+SJJE56HnlVpmPR5pcY+yn
        xKU0skXeQspIV0LIZ8MIycifNXPjdtdEGkvQ3GYi2pXtDvMC4COv5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T15:44:42Z"
  mac: ENC[AES256_GCM,data:BadylUGmuIeRxrdGxSztBgJGeV3GUUXqdJq0sT91ckSJGw3P08vw4sowU/3nSVVMaPBFpWLiaUt4CuBKIlG7JM3nYoRZngPPSO00wWRBEXdrXz8wl1mI9yw92jV724vXUhWwQkw4B2KL/qNp+v+QxIG/GHRckAN1r8UP+ZF/VaE=,iv:Vh4nrZ0wOuOVIZBeuBhihlvQ2drYbd5kk3jlhn78wpw=,tag:fRsYXdZqqMD576ck2snPcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
