# NOTE: placeholder until you set a real admin password and encrypt.
# 1. Replace the placeholder below
# 2. sops --encrypt --in-place kubernetes/apps/observability/grafana-operator/instance/grafana-admin-secret.sops.yaml
# Do not commit/push this file while it contains plaintext.
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:0USvcqZ83LrlsTTEy5Gffw4UuUzVbnKQfbCjUtJauIQFUdpB5eeCcvXkABLzzg==,iv:JGmy3A0G5E3ithfWMmkb++sppDq8a1sGV/pPpPjochA=,tag:snHSpNGllFxtHImM5Yecqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a3RpT3k2akdLTXJXaWN0
        VXpQRmo3RlFsL3hNL1V5Y0tTWGZ3bW9wVEdrCkJDcS9aazJwSHZzNUNJR2sxY3li
        UDJvcjRsVGVqZGR3TTNmWlZ3cnpTc28KLS0tIDNkL1puOVR6cHFVd2k2dW5hcTZY
        cFZpTGNlTFp1UVQ2Wk11RldKYXRiZTAKoSaAiLjszzoQnsuAIYTDQv/Uztwd/lZF
        urgEo5oe9oUgZ9WTiq53jYT6Jev5qGXnmadD/ibH1hY300ciG9nXzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T10:57:34Z"
  mac: ENC[AES256_GCM,data:wbWhJNZ43a7ohzj0p2fssevBFTlegvvvpZGumWwc5FmC30NS4zQXyedRtV02GlbZnMVr0ZPBQoTFvygkRGjxK+iUhzsznyOHxX1VcPlHEXpfcAnh/Ak9yY1iRFo1E97K2c8X+I161f4x82LPngFLOzE+4tZyk+z+rYjm+xv3Ir8=,iv:mRg2ERF7ew9U4jIis7/Fa89pbFXYvHuOo93KNGZXfgg=,tag:vvGWZCSVzi20qg3plESwwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
