apiVersion: v1
kind: Secret
metadata:
  name: tg-s3-processor-secret
stringData:
  WORKER_URL: ENC[AES256_GCM,data:kMBnSiIF67s1Ipq40ols07Wk2cq3kkeXr3SL,iv:mEuLRDd4QL2GgwOP2+O099n3SvZf5/r0e32YIlzSIsY=,tag:7ynQWhjudemAiohANikXMQ==,type:str]
  PROCESSOR_AUTH_SECRET: ENC[AES256_GCM,data:V9y0m+krKTeUq0Q0CDpWz5u8o6XQpR37uUtrJVNNCP2ComQ5cTY0kWbQbYdMX0HlR6vIUZwblWlvBBmMy5e+ebeRoipxoxe9oyynd5ju9k4+o1Ee6vwnVc6dhzFqUiNvOom1L8icBKfuXH6LrsG/QJUvfHyNENJLTVo/xyY5QD8oiEtohvRw5VDoxpgZbWTja5eqr/NU+qxMnmeDhNxbxy37iwn/qdr7ZoFWsOZ+cRwwVFOFBh0p+v9RaRR8T49PkifsRH/BMQat7ecU/nP7E0KM5FY6tHrdR7N/WqxmzEakpcMfTdWLz9KOTkG6/Wdw+xvmlpSdwB4FcGBi228AaA==,iv:Sq3KJuKsDgrpKqbkoJBKYoO1xNmd0XpK18HveXpfJhY=,tag:XhHwnyRzFd2jKh2N079FAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NUdLSjNhekFjNmRMTmc0
        YjFpT3FTaW9DZk5rTXh5M1ZBZk5wSjlycEJZCnRySFBkalhGK0l1elc3ZmJIN3dz
        cm1ZWnlyZUNtTzF4YmJ1aVVuY0UydlkKLS0tIEd5aFYzb2NwOG1ITEFSM3JZVjFM
        aldEOFVybERnSUZmZkJFSDA2dHVPV2MKLKYPgt8Z6mveIm6myv31RYC/JeT75mqU
        5Dh26e7xY/x21hTRNr/57dEUtGquzllPyanjrPwpx6KFwMz+0S9tkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T01:11:07Z"
  mac: ENC[AES256_GCM,data:PDSeE03R+fqE7hdhQxOtkXw8NiTWnrsib99EF3IHi6qfIzfkNbdswyCRKVO01bmUFgOswCyBI7G4YcEE0qu1yaLJpvQ9/XaVs38OmGvqBVtxBH1ATWs5RQulxkepBUeWwQ97ByJljV/xg7i3NXOrR7RASP+3A1KBvKHAKMYX20w=,iv:Wcgoy6gE9ZBfHTchhNApk+3iqCn+YzblLeknwCTSMuA=,tag:JVI48HREoBQWjN7Thqi7bw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
