apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:IP+jxTQ1rx8+UWHy6G8rtdMac8uSshgiZ6tg4xh4WMZH8LZY4tZgrBYxo48S+8hDlvsC2r4EOEU2umyN+49ROJP3AYi94IY6DhsWfuv8TwqqVD/kRxvORiQmxyX+6LT/0efmG2fHlnVRs+Gg0jq86eO5QVDUX4AmUSXJhNzEEpbZTbkc7yJJDmKx9GSkJpZAwwTpKyTq8jSfEIqiMlCv8f8bvs9AceAEzXgAl9cTBlEkK7Uy,iv:WACCUX/1kiq/DcBWzQYGLrDQAn++TXP9PcBcymBpoVs=,tag:kdEBxYO+lLk8Oq8ErgwpqQ==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaUMyZENZOVRWak1oUkh6
        SnlsNjlSdlRnN2dLTGN6eU1leG1sdDFFMXpvCmkwcnFuSDZXdys4Y1dxZ3FoNUlG
        Y2pmZ1lzOWs4RHdST3hSV2w1dXdicUUKLS0tIGlLeG1VR3Z3U1kyUUZ2Z0poSkM4
        MmUyV3JFQVZpc1NtYmE2UCtMbzZQTEUKdFfT+CoXsWRv56nXhOssZ70B+9mJTrd4
        2fp/qmac+Lj6z1waEDpppqRiN9JCKjRZSJLQD3pADpHlY1sm6CFSJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T15:44:42Z"
  mac: ENC[AES256_GCM,data:khGJidg2efnMSQPxCnjlm1YtufTcmfJgPpb44YXeOOq66OHzdnn0cbPcw0L7ypu/62QhxMRShxgQKP9HZyT4jV1SE5/lNJ4RR4QtGD+04JrUQ03V0qsKg3WbM8gQqSGU5+L1gJenzYEY5EiDMGYDkSuGFeFk+GifmF/RnNYfbG4=,iv:tvQ4WEkqvJaux7LhM7zDt5R9uVndqr6QQFUouuaPlB4=,tag:bJhYYYvaEE9vwcNSRUu7rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
