apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6effoowxyiTvz6P5TaBV16mZ2+KxmjFqM7gdep4tU0zqv+Jj5HRXubsMFjXulRPjQF8Hywwu5wRkN0M2iVob/aUB2ZAxeUxdgfvPWp5N9I3etjStyNhNNtB4oiE2+En43C7pd8xEKTBIxDbJfohnIQWOvhfXwzD5MqbXrDMtMESjiXZG5Xoqvo0bkfNg89BbYLMfyS8oU2gHP2ubEjuV82vQ3aUjX9UbWbDmbR27p3gvktlu,iv:Vxbq8GDDpKgnjn95k5YeRa9B0wzpGZ1WaLhpYVs9qQk=,tag:pA7RpIS4Dl59doDcMWmVjg==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteTZRSnVIcFdPSW9LZlQx
        Rko0YWc3b2hRdVpBMHhyejQ1QlF3YkZMdURBCnpsSDFWNFBsaHIxUDlQVWNUbmdV
        cy92bnV4a3Yrc1EvUm51cGdZUmJidEUKLS0tIG9kVVRvakx2Vm9qMGcyU2lrMGVq
        V1BCWk1LenRMa1dTMHdUWGtVeGc3R1kK2dX0RbNEqw6iILUfCO1jXvwplZMHpwJz
        tgdJ2YtTOzXOJvJryDSisEadaA8IDLz21ts8QBOJ0i9orKgtvcdEBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T01:46:09Z"
  mac: ENC[AES256_GCM,data:sCO+2NuBaRcGCE69L5Jr4OtlldaAqMSsVFTTzzkc7IIFf5CPqgluriITYy+0NorA6Pj5aFHqg8zMYkM8VolT9b/IijJt59ekCJxkHNO/0W3eaCiNEZJ4clkiKfkg2Uz5NkmBG/HKx77wR63qvG43AkHmGs5+Xq3E94eHK/fIVWg=,iv:SgRkOlfvPwaM+XeME9Hk2MrGdj51rHcS8sGlLp+XaqM=,tag:JLr12iTBLi422QG/IbX0xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
