apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7oSTPfFSj+s0mzcoDpS+TydUWmTdKBRVhWQaFOidy8CTY4B5w/sdJA==,iv:hpJQgKuny/QMiyZVafDXm4Pv5NqYEOiLkQErdUC0jMk=,tag:prQSeQW+d751gBTVpz0jUQ==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRUVIdGtTK1dSTGdDNUxS
        N0Jhelk3YmNHS2hWZXBXM25jVEsxNDUvbzBBCk9Ra0MvVnR6Ny93NWwrdThHTzAz
        ZGxJbTBoUFdWMVVYVWlGRW5iWVViTkUKLS0tIENVWndmdzhrMXNabGhvdEV1MGtP
        WnVLb0NzcmltR1ZwSWtLMjNoTlA1L1UKP4XwPQnbjFr/uC1ls0XRbyNktZ5jnPEu
        BgsL8hsv1l8v1BOuNQuEtdT6vBjY4fCPCB+Np0o0apw98JJcHMlLmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T15:44:42Z"
  mac: ENC[AES256_GCM,data:SeA2lUOpdZAA/+jgQFnxinCwLEKxoFsc5dz5633ACUioZpiSXHMZNmt3JWv4wcaRigspN4H3eirEHM0N9k7o4eH07WhQD26NoQjmJSRD7nkHAAMust1Si3mCv+k7tTJEoFf/u7+z7bAfDhMgBfrBK0wFY9DCcHLuxmqW90KvpgI=,iv:HF48Igp1cvbQ2D7nviZop9h7lIm01Iiqwt4ZXS97fcs=,tag:aE3qTgvxtdVlSY35eIpP5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
