apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2tfboIrSKkvt09KbTPTJxxrRfL7rXyY+8Aq77R8W0MNvMWmg+iGmCg==,iv:Au3K9njLjsLL+7yUfl2z+lrdtjaQTMSltjIoIXytrlk=,tag:73WIfy1QEm5gcgP+0yF5cQ==,type:str]
sops:
  age:
    - recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Sno2TkRtamI4L202ZGYx
        ZTdTU2RTTDVpMDRCNkxBSGd2UENwcDU3cWtjCkRPbUJvcm4vQmxDdXhjclRpbExo
        YkpwK3U4eUQ4R0N0cVBSaHFldE5kbFkKLS0tIHJzNlo0SnIyMVRTTGYzanNGQTNE
        cE1scjVGUDdXS2syeE9ZUUt6NEljRkUKyPgYUE4HaWvgELVHLC8XSHfT3ZlXZkUB
        HoVbflWj3eoPtw2HeeVoak3kVVqwdDB5Ru8Jehf6mJO1tU0pukkqJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T01:46:09Z"
  mac: ENC[AES256_GCM,data:7XGv2UUdD9sJvGBsxCHZynm+BYBdDwCt+aQNQ0UODx4qc7oFN+GxWEKx0gBE7xT0VYkjYh0+9mOZ930IbsQM8FswjUvfTzHC7Ce7Oy++Xp6IJOkNMXAMNcczhzeseThY2RfK54atHRKqdeN5NrY5d0rn5f8052enrOUa+HKXmDQ=,iv:AyzIdopmN7rBVDx3U9CiEANqwuEF9SB9N1MObEcQDpo=,tag:lABVi3TGM0aewHe+o3ossg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
