apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:e4WfqRLCJC6+,iv:8OiPhZYfqIMRSVLMksmvJFu92enoGAY8LfMlfeMA97Q=,tag:9mWtyfPLNN4mqc4GKGwuFA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3CD/BK2NA8Lr3X0r00jVL32H9KXjc2G8QLO9+uwxKg7NGjyj,iv:twsZBqEcNfWpeBmcGDnsRjsAgQC4xzOVTGdAgtC2zVg=,tag:LEwVD47dS8BtOiL1vC6k0g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ekuhxwq50saudy95lf743dlpgt4etwswps09225ly999fdll795s0sv6el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZHk4d1U2RWpHOHMzUmtW
        NHlTUG5Fbyt5T2RaUitkUU0vRGZZRWpsWHdnCnIwQzlRM2hob1h1S2dxQWIzdWNa
        V1RTc1V6cnprNXFWL3NVbmgwVTNyNkkKLS0tIGFQSkt3SnNFaGZIZ0RIWVJBUnlE
        VWREejVjb0JaRDZEdVlEVjhMOWRYeWsKIhyNtW2rBEAPpjzRpdtd268AL711Yy8n
        2akO9NJoogO0v+CtvlD+/HLq5sfEvlfdyrOrRroiV17s8SkDNXOXgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T16:50:54Z"
  mac: ENC[AES256_GCM,data:3zGDvbacbwqZRpGwKuuolXo3hWjrFLEFW8zxbkBzjsOVgwQHiFKF7XJIwOjKDknrv2CC7byJazxvz2w42r76z+UiI6eRK1uiHvgxz/C1k+0o8yeg7U3W9A64yqGHDEH/dQDXB5vGZ1RieFnmvWMgt/pT99W6f/PEmEBx4WHmprQ=,iv:h5xImhinWdigDhEmKFQ5KxRR7dALfd9qqDIpqF5kdHo=,tag:eBnaFV9aP7gm6CRp+EXTtA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
