apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:9giOL43JiJRc0OZderJj3g==,iv:uzKk1qnDCgKCotoL4G9fsu3svRCYo9RyFWbubNDx3Qg=,tag:UNZH5Yz/u5B6bNc1M2mPEw==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:mT4J8JMaITqXGLWCg16fc84+oFrUfswXjbcNG6U6Dv4=,iv:qT0Af79q+yvQspO1o5QukFyi+vH2uMV2xrDGTAkgB3k=,tag:KMi8AVKANIaueUJ0riWqpg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdllsQzV1dk1tTjlVZTZP
        ditiYXMvYWVEamFwTGVWS3NQSStCOGMwN0hBCk1wYnNONkJsOWMvWjJSU1RlR204
        NmdxYko1Rko4T0VwaldVMktmSnZRcGMKLS0tIGxqeGl5M05peUZXa2NEdjljeWFj
        WXNPNldaUFRvQmIzM3VDU2YwOHkwUmsK9A32rxUpP/BEEI5m5Qw0Ke/czyMtijkh
        ZHVqDgq6c5XcRNndy+/EcXizvMjqUR0Zq6SFy0aZza2biXMQ1u3iuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T01:22:32Z"
  mac: ENC[AES256_GCM,data:NbjDfg7BM5N/HJtJZ7w5Zv8MNCUBGTBCzq4fx1+ps9TXLSWWPSHPacZnHvynoWTAdv795IWSiNsmxsbRvn9DsVbWBIucS6UO3Qj47vE6UId6T5br+TUcpiKQAtnIa5SUHRVuDBm4mNm19+gl3yHyBc5gxlYxse/w98AchfwWUw8=,iv:GnjAt8DfGx1Gr/LqEqOeTbYcarAZSQUpQMv88X+2Yr8=,tag:MdF7L+8of9ckTW3gCPEjEg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
