apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:KuLqhPCl1Wxhb41FuH6D/w==,iv:4QbPoIWevhZVQFX6UOEik6yz5BD1w1WmqSiFDLW80xM=,tag:rrw4evQy0GfD8WvIZ95FeA==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:uvKbW4dveFVmNVFPt0kOF/qvZhqpigyLm5ICptvLOL0=,iv:pzv1ZEBr1KXFDis1OOGMA8kJBREt9UT9qoNRHRunnio=,tag:1TnqeWKcdCdrwYZsT9t+/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHhtVUQxSzdTMDNscm51
        NFNiV2pFaG5UY3NDME04VVZjaXBnSW0raFU0CjQwVGZmOGgrWlhxa1JjcGNHcjlv
        RXN1TmFTaC80eHBHa1k2KzUvbWtMTTQKLS0tIFUzMEluaWJoR0d2QlAwOE9CN3E3
        blhUL2thcWl1SGtmNWVSd0pBSktvME0K1s4wgl7h53AyNKCxkmsxxoUci8VaxlAz
        ZWtL3DkJBZ1/NcEPKntqW2EEFcx//5DU7GMhpc7Iiy8iV1LwPQn3rA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T01:01:57Z"
  mac: ENC[AES256_GCM,data:WltBAkqodbOaUeA+SFl0h+9yAh2ZUtj/2/Ee+i0OoyYDnJiGK/ehAquNkdNMn/zn2TM3QATVsR+sNiLze+/ltBudvU5OOdFngClsxVUAA2yEDqpXNwzN+1B3U+mjsmhPNW/ok5IbJjFnOvDCdH3O11iw3ckWW/fLEJQqgj91iMQ=,iv:No7WQUXitMNVo4/Bq8Z8iHDDOs0901vb/nS7/gFBKDU=,tag:IH5Ymc8ssC/R4p1SeCHG8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
