apiVersion: v1
kind: Secret
metadata:
  name: tg-s3_processor-secret
stringData:
  WORKER_URL: ENC[AES256_GCM,data:XqBdHRlP/oXfAyZ0XzCBiflo/Bw=,iv:hdrdvXYge90D9xDb4Z/tyxoWeiwzkQRtFxc0e/T+PBQ=,tag:oZFpiDpZgFOixuKdPFJoRw==,type:str]
  PROCESSOR_AUTH_SECRET: ENC[AES256_GCM,data:V9y0m+krKTeUq0Q0CDpWz5u8o6XQpR37uUtrJVNNCP2ComQ5cTY0kWbQbYdMX0HlR6vIUZwblWlvBBmMy5e+ebeRoipxoxe9oyynd5ju9k4+o1Ee6vwnVc6dhzFqUiNvOom1L8icBKfuXH6LrsG/QJUvfHyNENJLTVo/xyY5QD8oiEtohvRw5VDoxpgZbWTja5eqr/NU+qxMnmeDhNxbxy37iwn/qdr7ZoFWsOZ+cRwwVFOFBh0p+v9RaRR8T49PkifsRH/BMQat7ecU/nP7E0KM5FY6tHrdR7N/WqxmzEakpcMfTdWLz9KOTkG6/Wdw+xvmlpSdwB4FcGBi228AaA==,iv:Sq3KJuKsDgrpKqbkoJBKYoO1xNmd0XpK18HveXpfJhY=,tag:XhHwnyRzFd2jKh2N079FAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NUdLSjNhekFjNmRMTmc0
        YjFpT3FTaW9DZk5rTXh5M1ZBZk5wSjlycEJZCnRySFBkalhGK0l1elc3ZmJIN3dz
        cm1ZWnlyZUNtTzF4YmJ1aVVuY0UydlkKLS0tIEd5aFYzb2NwOG1ITEFSM3JZVjFM
        aldEOFVybERnSUZmZkJFSDA2dHVPV2MKLKYPgt8Z6mveIm6myv31RYC/JeT75mqU
        5Dh26e7xY/x21hTRNr/57dEUtGquzllPyanjrPwpx6KFwMz+0S9tkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1658d87m9qz4fmvlqprxjr4xen79hule9pww4y54ah0kr75lw9suswy0ux7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-29T16:16:59Z"
  mac: ENC[AES256_GCM,data:01B4KAKCuR+ti9mthi7qbYGN0d7iJ6xKnwjvgPwUAhBF9YNX4lP6i7FBu3CfpWrBrnCAwE3dYeDaz/iTbKrZCJr6WHBAAFR30bD1W1OjOl0wqWSdMLBxfFBy5EJ5hTICim1EwLrRqUCymOUNQSkRd6faTRysfLnryujg2e8zlu0=,iv:08Bw1zPEy6XhZzoq2sEjYLoBA7Vrf8pg5WyEP5XityM=,tag:BBJGyy3t2JTKrLbRVnUVvw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
